### ISSUE TITLE
chevrons are not vertically centred

### ISSUE THREAD

**Issue by sgserg** [philipshurpik/Framework7-Contacts7-MVC#4]
They appear slightly raised.

**Comment by nolimits4web** [comment]
For this type of list they shouldn't be centred. Look at the iOS Mail app

**Comment by sgserg** [comment]
Oops. My bad)

**Comment by sgserg** [comment]
Must be the other stuff making it feel almost-but-less-than native
- less snappy forward/backward page slide animations
- no scroll to top
- no hairline separators
- slide-left-to-reveal-context-menu occasionally auto-hitting the discovered delete button
